//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaborAccounting
    {
        public int ID { get; set; }
        public int IDEmployee { get; set; }
        public int WorkingDays { get; set; }
        public int DaysWorked { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
